appConfig:
  logging:
    logLevel:
      Default: Information
      Microsoft.AspNetCore: Warning
  
  database: 
    name: "4b2_zukovnik_db1"
    connection:
      server: mysqlstudenti.litv.sssvt.cz
      userName: zukovnik
      password: 123456
      
  source:
    productImage: "/home/berbenzuel/school/prg/boots-eshop-mvc/BootEshop/BootEshop/Assets/Product/"
    carrouselImage: "/home/berbenzuel/school/prg/boots-eshop-mvc/BootEshop/BootEshop/Assets/Carrousel/"
    categoryImage: "/home/berbenzuel/school/prg/boots-eshop-mvc/BootEshop/BootEshop/Assets/Category/"